module.exports=(sequelize,DataTypes)=>{
    const patient=sequelize.define("patient",{
        name:{
            type:DataTypes.STRING,
            allowNull:false,
        },
        password:{
            type:DataTypes.STRING,
            allowNull:false,
        },
        address:{
            type:DataTypes.STRING,
            allowNull:false,
        },
        email:{
            type:DataTypes.STRING,
            allowNull:false,
        },
        phone:{
            type:DataTypes.STRING,
            allowNull:false,
        },
    });
    patient.associate=models=>{
        patient.hasMany(models.appoint,{
            onDelete:"cascade",
            onUpdate:"cascade"
        });
    };
    return patient;
}